name: Continuous Build
on: push

jobs:
  build:
    name: Build Templar

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-musl
            use-cross: true
            run-tests: false
            ext: ''
          - os: ubuntu-latest
            toolchain: stable
            target: aarch64-unknown-linux-musl
            use-cross: true
            run-tests: false
            ext: ''
          - os: ubuntu-latest
            toolchain: stable
            target: armv7-unknown-linux-musleabihf
            use-cross: true
            run-tests: false
            ext: ''
          - os: windows-latest
            toolchain: stable-msvc
            target: x86_64-pc-windows-msvc
            use-cross: false
            run-tests: false
            ext: '.exe'
          - os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin
            use-cross: false
            run-tests: false
            ext: ''

    runs-on: '${{ matrix.os }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: '${{ matrix.target }}'
          override: true
          default: true

      - name: 'Build binary for ${{ matrix.target }}'
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: '--all-features --target ${{ matrix.target }}'

      - name: 'Run tests for ${{ matrix.target }}'
        uses: actions-rs/cargo@v1
        if: matrix.run-tests
        with:
          use-cross: ${{ matrix.use-cross }}
          command: test
          args: '--all-features --target ${{ matrix.target }}'
